import express from 'express';import fs from 'fs';import path from 'path';import {PDFDocument,StandardFonts,rgb} from 'pdf-lib';import Document from '../models/Document.js';import {auth} from '../middleware/auth.js';import {mem,mongoReady,id} from '../services/store.js';
const r=express.Router();const uploadDir=path.join(process.cwd(),'uploads');r.use(auth);
async function getDoc(documentId,owner){return mongoReady()?Document.findOne({_id:documentId,owner}):mem.docs.find(d=>d.id===documentId&&d.owner===owner)}
function cleanPdfTitle(title='document'){return String(title||'document').replace(/\.pdf$/i,'').replace(/[^a-zA-Z0-9._-]+/g,'_').slice(0,80)||'document'}
async function savePdf(owner,title,bytes,tags=[]){const filename=`${Date.now()}-${cleanPdfTitle(title)}.pdf`;fs.writeFileSync(path.join(uploadDir,filename),bytes);const data={owner,title:cleanPdfTitle(title)+'.pdf',originalName:cleanPdfTitle(title)+'.pdf',mime:'application/pdf',size:bytes.length,path:filename,url:`/uploads/${filename}`,text:'',language:'auto',tags:['advanced-engine',...tags],createdAt:new Date()};const doc=mongoReady()?await Document.create(data):{id:id(),...data};if(!mongoReady())mem.docs.push(doc);return doc}
async function extractTextBlocks(filePath){const pdfjs=await import('pdfjs-dist/legacy/build/pdf.mjs');const data=new Uint8Array(fs.readFileSync(filePath));const loadingTask=pdfjs.getDocument({data,disableWorker:true});const pdf=await loadingTask.promise;const pages=[];for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p);const viewport=page.getViewport({scale:1});const content=await page.getTextContent();const items=content.items.map((it,idx)=>{const tx=it.transform||[1,0,0,1,0,0];const x=tx[4], y=viewport.height-tx[5];return{id:`p${p}-t${idx}`,page:p,text:String(it.str||''),x,y,width:it.width||0,height:Math.abs(tx[3]||10),fontName:it.fontName||'',confidence:it.str?'text-layer':'empty'}}).filter(i=>i.text.trim());pages.push({page:p,width:viewport.width,height:viewport.height,items});}return{pageCount:pdf.numPages,pages}}
r.get('/:id/text-blocks',async(req,res)=>{const d=await getDoc(req.params.id,req.user.id);if(!d)return res.status(404).json({error:'Document not found'});try{const blocks=await extractTextBlocks(path.join(uploadDir,d.path));res.json({documentId:req.params.id,editable:blocks.pages.some(p=>p.items.length),mode:'text-layer-inspection',blocks})}catch(e){res.status(500).json({error:'Text block extraction failed',detail:e.message})}});
r.post('/:id/replace-block',async(req,res)=>{const d=await getDoc(req.params.id,req.user.id);if(!d)return res.status(404).json({error:'Document not found'});const {page=1,x=72,y=720,width=260,height=24,text='Replacement text',fontSize=11}=req.body||{};try{const pdf=await PDFDocument.load(fs.readFileSync(path.join(uploadDir,d.path)));const font=await pdf.embedFont(StandardFonts.Helvetica);const pg=pdf.getPage(Math.max(0,Number(page)-1));const pageHeight=pg.getHeight();const px=Number(x), py=pageHeight-Number(y)-Number(height);pg.drawRectangle({x:px,y:py,width:Number(width),height:Number(height)+4,color:rgb(1,1,1),opacity:1});pg.drawText(String(text).slice(0,1000),{x:px,y:py+4,size:Number(fontSize),font,color:rgb(.05,.05,.05),maxWidth:Number(width)});const out=await pdf.save();res.json({document:await savePdf(req.user.id,`${d.title||'document'}-text-edited`,out,['text-replace']),warning:'Safe block replacement overlays the selected area. Full paragraph reflow is a later engine milestone.'})}catch(e){res.status(500).json({error:'Text replacement failed',detail:e.message})}});
r.get('/:id/ocr-status',async(req,res)=>{const d=await getDoc(req.params.id,req.user.id);if(!d)return res.status(404).json({error:'Document not found'});let textLayer=false;try{const b=await extractTextBlocks(path.join(uploadDir,d.path));textLayer=b.pages.some(p=>p.items.length>0)}catch{}res.json({documentId:req.params.id,textLayer,ocrEngine:'tesseract.js-installed',advancedOcrEditing:'planned',supportedNow:['detect text layer','extract positioned text blocks','safe block replacement overlay'],notFaked:['paragraph reflow','font-preserving arbitrary text edit','OCR correction UI']})});
export default r;
