import express from 'express';import fs from 'fs';import path from 'path';import {execFile} from 'child_process';import {promisify} from 'util';import {PDFDocument} from 'pdf-lib';import multer from 'multer';import Document from '../models/Document.js';import {auth} from '../middleware/auth.js';import {mem,mongoReady,id} from '../services/store.js';
const run=promisify(execFile);const r=express.Router();const uploadDir=path.join(process.cwd(),'uploads');const conversionDir=path.join(uploadDir,'conversions');fs.mkdirSync(conversionDir,{recursive:true});
const imgUpload=multer({storage:multer.diskStorage({destination:uploadDir,filename:(req,file,cb)=>cb(null,Date.now()+'-'+file.originalname.replace(/[^a-zA-Z0-9._-]/g,'_'))}),limits:{fileSize:20*1024*1024},fileFilter:(req,file,cb)=>/^image\/(png|jpeg|jpg|webp)$/.test(file.mimetype)?cb(null,true):cb(new Error('Only image uploads are allowed'))});
r.use(auth);
async function getDoc(documentId,owner){return mongoReady()?Document.findOne({_id:documentId,owner}):mem.docs.find(d=>d.id===documentId&&d.owner===owner)}
async function saveDoc(owner,title,filePath,mime='application/pdf',tags=[]){const filename=path.basename(filePath);const data={owner,title,originalName:title,mime,size:fs.statSync(filePath).size,path:filename.includes('conversions/')?filename:filename,url:`/uploads/${filename}`,text:'',language:'auto',tags,createdAt:new Date()};const doc=mongoReady()?await Document.create(data):{id:id(),...data};if(!mongoReady())mem.docs.push(doc);return doc}
r.post('/:id/to-images',async(req,res)=>{const d=await getDoc(req.params.id,req.user.id);if(!d)return res.status(404).json({error:'Document not found'});const src=path.join(uploadDir,d.path);const prefix=path.join(conversionDir,`${Date.now()}-${(d.title||'document').replace(/[^a-zA-Z0-9._-]/g,'_')}`);try{await run('pdftoppm',['-png','-r',String(req.body.dpi||144),src,prefix],{timeout:120000});const files=fs.readdirSync(conversionDir).filter(f=>f.startsWith(path.basename(prefix))&&f.endsWith('.png')).sort();res.json({images:files.map(f=>({url:`/uploads/conversions/${f}`,file:f})),count:files.length})}catch(e){res.status(501).json({error:'PDF image export requires poppler-utils on the host',detail:e.message})}});
r.post('/images-to-pdf',imgUpload.array('images',50),async(req,res)=>{if(!req.files?.length)return res.status(400).json({error:'Upload one or more images'});const pdf=await PDFDocument.create();for(const file of req.files){const bytes=fs.readFileSync(file.path);let img;if(file.mimetype.includes('png'))img=await pdf.embedPng(bytes);else img=await pdf.embedJpg(bytes);const page=pdf.addPage([img.width,img.height]);page.drawImage(img,{x:0,y:0,width:img.width,height:img.height});}const filename=`${Date.now()}-images-to-pdf.pdf`;const out=path.join(uploadDir,filename);fs.writeFileSync(out,await pdf.save());res.json({document:await saveDoc(req.user.id,req.body.title||'images-to-pdf.pdf',out,'application/pdf',['convert','images-to-pdf'])})});
r.post('/:id/to-text',async(req,res)=>{const d=await getDoc(req.params.id,req.user.id);if(!d)return res.status(404).json({error:'Document not found'});res.json({text:d.text||'',extractable:!!d.text,characters:(d.text||'').length,note:d.text?'Text extracted from PDF parser.':'No embedded text found. Scanned PDFs need OCR.'})});
r.post('/:id/ocr-status',async(req,res)=>{res.json({ready:false,engine:'planned-tesseract/azure-vision',languages:['eng','ara','fra','spa','deu','hin','urd'],note:'OCR endpoint is reserved. Install OCR engine/provider key to enable scanned PDF extraction.'})});
export default r;
