import express from 'express';
import fs from 'fs';
import path from 'path';
import { PDFDocument, StandardFonts, rgb, degrees } from 'pdf-lib';
import Document from '../models/Document.js';
import { auth } from '../middleware/auth.js';
import { mem, mongoReady, id } from '../services/store.js';
const r=express.Router();r.use(auth);
const uploadDir=path.join(process.cwd(),'uploads');
async function getDoc(docId, owner){return mongoReady()?Document.findOne({_id:docId,owner}):mem.docs.find(x=>x.id===docId&&x.owner===owner)}
async function savePdf(owner,title,bytes,meta={}){const filename=`${Date.now()}-${title.replace(/[^a-zA-Z0-9._-]/g,'_')}.pdf`;fs.writeFileSync(path.join(uploadDir,filename),bytes);const data={owner,title,originalName:title,mime:'application/pdf',size:bytes.length,path:filename,url:`/uploads/${filename}`,text:'',language:'auto',tags:['generated','pdf-tool',...(meta.tags||[])],createdAt:new Date()};const doc=mongoReady()?await Document.create(data):{id:id(),...data};if(!mongoReady())mem.docs.push(doc);return doc}
function pageIndexes(spec,total){if(!spec)return [...Array(total).keys()];return String(spec).split(',').flatMap(part=>{if(part.includes('-')){let[a,b]=part.split('-').map(n=>parseInt(n,10));a=Math.max(1,a);b=Math.min(total,b);return Array.from({length:Math.max(0,b-a+1)},(_,i)=>a-1+i)}const n=parseInt(part,10);return Number.isFinite(n)&&n>=1&&n<=total?[n-1]:[]})}
r.post('/:id/rotate',async(req,res)=>{const d=await getDoc(req.params.id,req.user.id);if(!d)return res.status(404).json({error:'Document not found'});const pdf=await PDFDocument.load(fs.readFileSync(path.join(uploadDir,d.path)));const angle=Number(req.body.angle||90);for(const p of pdf.getPages())p.setRotation(degrees(((p.getRotation().angle||0)+angle)%360));const out=await pdf.save();res.json({document:await savePdf(req.user.id,`${d.title||'document'}-rotated.pdf`,out,{tags:['rotate']})})});
r.post('/:id/extract',async(req,res)=>{const d=await getDoc(req.params.id,req.user.id);if(!d)return res.status(404).json({error:'Document not found'});const src=await PDFDocument.load(fs.readFileSync(path.join(uploadDir,d.path)));const idx=pageIndexes(req.body.pages,src.getPageCount());const outPdf=await PDFDocument.create();const pages=await outPdf.copyPages(src,idx);pages.forEach(p=>outPdf.addPage(p));res.json({document:await savePdf(req.user.id,`${d.title||'document'}-extract.pdf`,await outPdf.save(),{tags:['extract']})})});
r.post('/:id/delete-pages',async(req,res)=>{const d=await getDoc(req.params.id,req.user.id);if(!d)return res.status(404).json({error:'Document not found'});const src=await PDFDocument.load(fs.readFileSync(path.join(uploadDir,d.path)));const del=new Set(pageIndexes(req.body.pages,src.getPageCount()));const keep=[...Array(src.getPageCount()).keys()].filter(i=>!del.has(i));const outPdf=await PDFDocument.create();const pages=await outPdf.copyPages(src,keep);pages.forEach(p=>outPdf.addPage(p));res.json({document:await savePdf(req.user.id,`${d.title||'document'}-pages-removed.pdf`,await outPdf.save(),{tags:['delete-pages']})})});
r.post('/:id/watermark',async(req,res)=>{const d=await getDoc(req.params.id,req.user.id);if(!d)return res.status(404).json({error:'Document not found'});const pdf=await PDFDocument.load(fs.readFileSync(path.join(uploadDir,d.path)));const font=await pdf.embedFont(StandardFonts.HelveticaBold);const text=req.body.text||'VELLUM';for(const page of pdf.getPages()){const{width,height}=page.getSize();page.drawText(text,{x:width*.18,y:height*.48,size:48,font,color:rgb(.78,.63,.31),opacity:.18,rotate:degrees(-30)})}res.json({document:await savePdf(req.user.id,`${d.title||'document'}-watermarked.pdf`,await pdf.save(),{tags:['watermark']})})});
r.post('/:id/stamp',async(req,res)=>{const d=await getDoc(req.params.id,req.user.id);if(!d)return res.status(404).json({error:'Document not found'});const pdf=await PDFDocument.load(fs.readFileSync(path.join(uploadDir,d.path)));const font=await pdf.embedFont(StandardFonts.HelveticaBold);const text=req.body.text||'APPROVED';const page=pdf.getPage(Number(req.body.page||1)-1);page.drawRectangle({x:36,y:36,width:180,height:48,borderColor:rgb(.78,.63,.31),borderWidth:2,color:rgb(.05,.12,.09),opacity:.85});page.drawText(text,{x:52,y:54,size:18,font,color:rgb(.96,.94,.9)});res.json({document:await savePdf(req.user.id,`${d.title||'document'}-stamped.pdf`,await pdf.save(),{tags:['stamp']})})});
r.post('/merge',async(req,res)=>{const ids=Array.isArray(req.body.ids)?req.body.ids:[];if(ids.length<2)return res.status(400).json({error:'Provide at least two document ids'});const out=await PDFDocument.create();for(const docId of ids){const d=await getDoc(docId,req.user.id);if(!d)continue;const src=await PDFDocument.load(fs.readFileSync(path.join(uploadDir,d.path)));const pages=await out.copyPages(src,src.getPageIndices());pages.forEach(p=>out.addPage(p));}res.json({document:await savePdf(req.user.id,req.body.title||'merged-document.pdf',await out.save(),{tags:['merge']})})});
r.get('/capabilities/list',(req,res)=>res.json({capabilities:['view','upload','search','analyze','chat','generate','sign-evidence','rotate','extract-pages','delete-pages','watermark','stamp','merge','arabic-rtl','backend-only-ai']}));
export default r;
