import express from 'express';
import fs from 'fs';
import path from 'path';
import { PDFDocument, StandardFonts, rgb, degrees } from 'pdf-lib';
import Document from '../models/Document.js';
import { auth } from '../middleware/auth.js';
import { mem, mongoReady, id } from '../services/store.js';
const r=express.Router();r.use(auth);
const uploadDir=path.join(process.cwd(),'uploads');
async function getDoc(docId, owner){return mongoReady()?Document.findOne({_id:docId,owner}):mem.docs.find(x=>x.id===docId&&x.owner===owner)}
async function savePdf(owner,title,bytes,meta={}){const filename=`${Date.now()}-${title.replace(/[^a-zA-Z0-9._-]/g,'_')}.pdf`;fs.writeFileSync(path.join(uploadDir,filename),bytes);const data={owner,title,originalName:title,mime:'application/pdf',size:bytes.length,path:filename,url:`/uploads/${filename}`,text:'',language:'auto',tags:['generated','pdf-tool',...(meta.tags||[])],createdAt:new Date()};const doc=mongoReady()?await Document.create(data):{id:id(),...data};if(!mongoReady())mem.docs.push(doc);return doc}
function pageIndexes(spec,total){if(!spec)return [...Array(total).keys()];return String(spec).split(',').flatMap(part=>{if(part.includes('-')){let[a,b]=part.split('-').map(n=>parseInt(n,10));a=Math.max(1,a);b=Math.min(total,b);return Array.from({length:Math.max(0,b-a+1)},(_,i)=>a-1+i)}const n=parseInt(part,10);return Number.isFinite(n)&&n>=1&&n<=total?[n-1]:[]})}
r.post('/:id/rotate',async(req,res)=>{const d=await getDoc(req.params.id,req.user.id);if(!d)return res.status(404).json({error:'Document not found'});const pdf=await PDFDocument.load(fs.readFileSync(path.join(uploadDir,d.path)));const angle=Number(req.body.angle||90);for(const p of pdf.getPages())p.setRotation(degrees(((p.getRotation().angle||0)+angle)%360));const out=await pdf.save();res.json({document:await savePdf(req.user.id,`${d.title||'document'}-rotated.pdf`,out,{tags:['rotate']})})});
r.post('/:id/extract',async(req,res)=>{const d=await getDoc(req.params.id,req.user.id);if(!d)return res.status(404).json({error:'Document not found'});const src=await PDFDocument.load(fs.readFileSync(path.join(uploadDir,d.path)));const idx=pageIndexes(req.body.pages,src.getPageCount());const outPdf=await PDFDocument.create();const pages=await outPdf.copyPages(src,idx);pages.forEach(p=>outPdf.addPage(p));res.json({document:await savePdf(req.user.id,`${d.title||'document'}-extract.pdf`,await outPdf.save(),{tags:['extract']})})});
r.post('/:id/delete-pages',async(req,res)=>{const d=await getDoc(req.params.id,req.user.id);if(!d)return res.status(404).json({error:'Document not found'});const src=await PDFDocument.load(fs.readFileSync(path.join(uploadDir,d.path)));const del=new Set(pageIndexes(req.body.pages,src.getPageCount()));const keep=[...Array(src.getPageCount()).keys()].filter(i=>!del.has(i));const outPdf=await PDFDocument.create();const pages=await outPdf.copyPages(src,keep);pages.forEach(p=>outPdf.addPage(p));res.json({document:await savePdf(req.user.id,`${d.title||'document'}-pages-removed.pdf`,await outPdf.save(),{tags:['delete-pages']})})});
r.post('/:id/watermark',async(req,res)=>{const d=await getDoc(req.params.id,req.user.id);if(!d)return res.status(404).json({error:'Document not found'});const pdf=await PDFDocument.load(fs.readFileSync(path.join(uploadDir,d.path)));const font=await pdf.embedFont(StandardFonts.HelveticaBold);const text=req.body.text||'VELLUM';for(const page of pdf.getPages()){const{width,height}=page.getSize();page.drawText(text,{x:width*.18,y:height*.48,size:48,font,color:rgb(.78,.63,.31),opacity:.18,rotate:degrees(-30)})}res.json({document:await savePdf(req.user.id,`${d.title||'document'}-watermarked.pdf`,await pdf.save(),{tags:['watermark']})})});
r.post('/:id/stamp',async(req,res)=>{const d=await getDoc(req.params.id,req.user.id);if(!d)return res.status(404).json({error:'Document not found'});const pdf=await PDFDocument.load(fs.readFileSync(path.join(uploadDir,d.path)));const font=await pdf.embedFont(StandardFonts.HelveticaBold);const text=req.body.text||'APPROVED';const page=pdf.getPage(Number(req.body.page||1)-1);page.drawRectangle({x:36,y:36,width:180,height:48,borderColor:rgb(.78,.63,.31),borderWidth:2,color:rgb(.05,.12,.09),opacity:.85});page.drawText(text,{x:52,y:54,size:18,font,color:rgb(.96,.94,.9)});res.json({document:await savePdf(req.user.id,`${d.title||'document'}-stamped.pdf`,await pdf.save(),{tags:['stamp']})})});
r.post('/merge',async(req,res)=>{const ids=Array.isArray(req.body.ids)?req.body.ids:[];if(ids.length<2)return res.status(400).json({error:'Provide at least two document ids'});const out=await PDFDocument.create();for(const docId of ids){const d=await getDoc(docId,req.user.id);if(!d)continue;const src=await PDFDocument.load(fs.readFileSync(path.join(uploadDir,d.path)));const pages=await out.copyPages(src,src.getPageIndices());pages.forEach(p=>out.addPage(p));}res.json({document:await savePdf(req.user.id,req.body.title||'merged-document.pdf',await out.save(),{tags:['merge']})})});

r.post('/:id/annotate',async(req,res)=>{const d=await getDoc(req.params.id,req.user.id);if(!d)return res.status(404).json({error:'Document not found'});const pdf=await PDFDocument.load(fs.readFileSync(path.join(uploadDir,d.path)));const font=await pdf.embedFont(StandardFonts.Helvetica);const page=pdf.getPage(Math.max(0,Number(req.body.page||1)-1));const {width,height}=page.getSize();const x=Number(req.body.x??48), y=Number(req.body.y??height-96);const text=String(req.body.text||'VELLUM note').slice(0,500);const color=req.body.color==='red'?rgb(.78,.25,.2):req.body.color==='green'?rgb(.35,.62,.44):rgb(.78,.63,.31);if(req.body.kind==='highlight'){page.drawRectangle({x,y,width:Number(req.body.width||220),height:Number(req.body.height||22),color,opacity:.28});}else{page.drawRectangle({x,y,width:Math.min(width-x-24,Number(req.body.width||260)),height:Number(req.body.height||72),color:rgb(.96,.94,.9),opacity:.94,borderColor:color,borderWidth:1});page.drawText(text,{x:x+10,y:y+Number(req.body.height||72)-24,size:11,font,color:rgb(.05,.12,.09),maxWidth:Math.min(width-x-44,Number(req.body.width||240))});}res.json({document:await savePdf(req.user.id,`${d.title||'document'}-annotated.pdf`,await pdf.save(),{tags:['annotate']})})});
r.post('/:id/redact',async(req,res)=>{const d=await getDoc(req.params.id,req.user.id);if(!d)return res.status(404).json({error:'Document not found'});const pdf=await PDFDocument.load(fs.readFileSync(path.join(uploadDir,d.path)));const pages=pdf.getPages();const boxes=Array.isArray(req.body.boxes)?req.body.boxes:[req.body];for(const b of boxes){const page=pages[Math.max(0,Math.min(pages.length-1,Number(b.page||1)-1))];page.drawRectangle({x:Number(b.x||48),y:Number(b.y||48),width:Number(b.width||220),height:Number(b.height||28),color:rgb(0,0,0),opacity:1});}res.json({document:await savePdf(req.user.id,`${d.title||'document'}-redacted.pdf`,await pdf.save(),{tags:['redact']})})});
r.post('/:id/reorder',async(req,res)=>{const d=await getDoc(req.params.id,req.user.id);if(!d)return res.status(404).json({error:'Document not found'});const src=await PDFDocument.load(fs.readFileSync(path.join(uploadDir,d.path)));const total=src.getPageCount();const order=(Array.isArray(req.body.order)?req.body.order:String(req.body.order||'').split(',')).map(n=>Number(n)-1).filter(n=>Number.isInteger(n)&&n>=0&&n<total);if(!order.length)return res.status(400).json({error:'Provide page order like 2,1,3'});const out=await PDFDocument.create();const pages=await out.copyPages(src,order);pages.forEach(p=>out.addPage(p));res.json({document:await savePdf(req.user.id,`${d.title||'document'}-reordered.pdf`,await out.save(),{tags:['reorder']})})});
r.post('/:id/insert-blank',async(req,res)=>{const d=await getDoc(req.params.id,req.user.id);if(!d)return res.status(404).json({error:'Document not found'});const src=await PDFDocument.load(fs.readFileSync(path.join(uploadDir,d.path)));const out=await PDFDocument.create();const at=Math.max(1,Number(req.body.afterPage||src.getPageCount()));for(let i=0;i<src.getPageCount();i++){const [p]=await out.copyPages(src,[i]);out.addPage(p);if(i+1===at)out.addPage([595.28,841.89]);}res.json({document:await savePdf(req.user.id,`${d.title||'document'}-blank-inserted.pdf`,await out.save(),{tags:['insert-blank']})})});
r.post('/:id/duplicate-page',async(req,res)=>{const d=await getDoc(req.params.id,req.user.id);if(!d)return res.status(404).json({error:'Document not found'});const src=await PDFDocument.load(fs.readFileSync(path.join(uploadDir,d.path)));const pageNo=Math.max(1,Math.min(src.getPageCount(),Number(req.body.page||1)));const out=await PDFDocument.create();for(let i=0;i<src.getPageCount();i++){const [p]=await out.copyPages(src,[i]);out.addPage(p);if(i+1===pageNo){const [dup]=await out.copyPages(src,[i]);out.addPage(dup);}}res.json({document:await savePdf(req.user.id,`${d.title||'document'}-page-duplicated.pdf`,await out.save(),{tags:['duplicate-page']})})});
r.post('/:id/compress',async(req,res)=>{const d=await getDoc(req.params.id,req.user.id);if(!d)return res.status(404).json({error:'Document not found'});const src=await PDFDocument.load(fs.readFileSync(path.join(uploadDir,d.path)),{ignoreEncryption:true});const out=await src.save({useObjectStreams:true,addDefaultPage:false});res.json({document:await savePdf(req.user.id,`${d.title||'document'}-optimized.pdf`,out,{tags:['compress']}),note:'Optimized PDF object streams. Image downsampling is planned for the next engine pass.'})});
r.post('/:id/export-text',async(req,res)=>{const d=await getDoc(req.params.id,req.user.id);if(!d)return res.status(404).json({error:'Document not found'});const body=d.text||'No extractable text found in this PDF. OCR pass required.';res.setHeader('Content-Type','text/plain; charset=utf-8');res.setHeader('Content-Disposition',`attachment; filename="${(d.title||'document').replace(/[^a-z0-9._-]/gi,'_')}.txt"`);res.send(body)});

r.get('/capabilities/list',(req,res)=>res.json({capabilities:['view','upload','search','analyze','chat','generate','sign-evidence','rotate','extract-pages','delete-pages','watermark','stamp','merge','arabic-rtl','backend-only-ai','annotate','highlight','redact','reorder-pages','insert-blank-page','duplicate-page','compress','export-text']}));
export default r;
