import 'dotenv/config';
import express from 'express';import cors from 'cors';import helmet from 'helmet';import rateLimit from 'express-rate-limit';import path from 'path';import {fileURLToPath} from 'url';import mongoose from 'mongoose';
import authRoutes from './routes/auth.js';import docRoutes from './routes/documents.js';import aiRoutes from './routes/ai.js';import signRoutes from './routes/signatures.js';import autoRoutes from './routes/automation.js';import toolRoutes from './routes/tools.js';import shareRoutes from './routes/share.js';import teamRoutes from './routes/team.js';import formRoutes from './routes/forms.js';
const __dirname=path.dirname(fileURLToPath(import.meta.url));const app=express();
const origins=(process.env.CORS_ORIGINS||'http://localhost:5173,http://127.0.0.1:5173').split(',');
app.use(helmet({crossOriginResourcePolicy:{policy:'cross-origin'}}));app.use(cors({origin:(o,cb)=>!o||origins.includes(o)?cb(null,true):cb(new Error('CORS blocked')),credentials:true}));app.use(express.json({limit:'5mb'}));app.use(rateLimit({windowMs:15*60*1000,limit:500}));
app.use('/uploads',express.static(path.join(__dirname,'uploads')));
app.get('/api/health',(req,res)=>res.json({ok:true,service:'vellum-document-os',database:mongoose.connection.readyState===1?'mongo':'memory-fallback',time:new Date().toISOString()}));
app.use('/api/auth',authRoutes);app.use('/api/documents',docRoutes);app.use('/api/ai',aiRoutes);app.use('/api/signatures',signRoutes);app.use('/api/automation',autoRoutes);app.use('/api/tools',toolRoutes);app.use('/api/share',shareRoutes);app.use('/api/team',teamRoutes);app.use('/api/forms',formRoutes);
app.use((err,req,res,next)=>{console.error(err);res.status(err.status||500).json({error:err.message||'Server error'});});
const PORT=process.env.PORT||8080;async function start(){if(process.env.MONGO_URI){try{await mongoose.connect(process.env.MONGO_URI);console.log('Mongo connected');}catch(e){console.warn('Mongo unavailable, using memory fallback:',e.message)}}else console.warn('MONGO_URI missing, using memory fallback for local dev only');app.listen(PORT,()=>console.log(`VELLUM API on ${PORT}`));}start();
